/**
 * THE VENDOR'S NUMBERS, TURNED INTO THIS DOMAIN'S POINTS — and every line of it is here, in the
 * host, because the package may not hold any of it.
 *
 * `lightweight-charts-indicators` is 1.05 MB of arithmetic and 320 offered names. `src/` gains none
 * of it: `test/boundary.spec.ts` bans the specifier and the entry's byte ceiling would refuse the
 * bytes anyway. What crosses the seam is what this file produces — a `PlottableSource` per chosen
 * study, and a plain value per control the workspace stores and never reads.
 *
 * ── EVERY POINT IS BUILT FROM THE BAR INDEX, AND THAT IS A DEFENCE, NOT A STYLE ────────────────
 *
 * The timestamp is the HOST's; only the value is the vendor's. `src/indicator/availability.ts`
 * aligns by timestamp with LAST WRITE WINNING, so a point the vendor stamps with a neighbour's bar
 * time is not discarded as off-grid — it OVERWRITES the reading that belongs to that neighbour.
 * `double-macd` does exactly that, two bars back, which is why the catalogue excludes it; but
 * excluding one entry treats one symptom. Reading the time off `bars[index]` removes the vector for
 * all of them at once, and it is sound because full-length index alignment is measured rather than
 * hoped for: 457/457 across the registry.
 *
 * ── A VALUE THAT IS NOT A NUMBER IS A DECLARED GAP, NEVER A ZERO ───────────────────────────────
 *
 * The vendor marks its warm-up with `NaN` and, on short windows, with `null`. This domain says a
 * `Point` WITHOUT `value` is a gap and draws nothing there, while a zero is a reading — the loudest
 * possible mark for the emptiest possible reason. `readingOf` already reads a non-finite as `null`,
 * so the conversion belongs where the vendor's shape is translated, which is here.
 *
 * ── THE PLOT KEY COMES FROM THE MANIFEST, WHICH READ IT OFF `plotConfig` ───────────────────────
 *
 * 42 of the 320 offered entries carry a key that is not `plotN` — `trendLine`, `exitLine`, `plotU`.
 * Assuming `plot0` would draw a quarter of the catalogue as an empty lane. The manifest carries the
 * keys the vendor declares and does not hide, and this file draws those and only those.
 *
 * ── THE `unknown` IS NARROWED HERE ─────────────────────────────────────────────────────────────
 *
 * `StudySettings` is `unknown` on purpose: the compiler refuses the package a property read, which
 * is what keeps the vendor's vocabulary out of `src/`. The narrowing is the host's obligation, and
 * it REFUSES an out-of-range value rather than clamping it — a value silently rewritten is a value
 * the user did not choose, arriving back on every load.
 */
import type {
  Bar,
  PlottableSource,
  PlottedSeries,
  Point,
  SeriesCatalogueEntry,
  SourceLookup,
  StudySettings,
} from 'lightweight-magic-charts';
import { seriesId, utcSeconds } from 'lightweight-magic-charts';

import manifestJson from './indicators/manifest.json';
import { plainRecord, readStudyValues } from './studyValues';
import type { ManifestInput, ManifestRow, StudyValue, StudyValues } from './studyValues';

/* ---- what the committed manifest promises ------------------------------------------------- */

/**
 * The value layer lives in `studyValues.ts` and is re-exported here, so a reader of the adapter
 * finds the whole vocabulary in one place while the FORM can import the reader without dragging
 * 182 KB of catalogue into the boot chunk behind it.
 */
export type { ManifestInput, ManifestRow, StudyValue, StudyValues } from './studyValues';
export { acceptValue, readStudyValues } from './studyValues';

const rowsOf = (raw: unknown): readonly ManifestRow[] => {
  const held = (raw as { readonly indicators?: unknown } | null)?.indicators;
  return Array.isArray(held) ? (held as readonly ManifestRow[]) : [];
};

/** The curated catalogue, as committed. Generated by `scripts/build-indicator-manifest.mjs`. */
export const MANIFEST_ROWS: readonly ManifestRow[] = rowsOf(manifestJson);

/* ---- the vendor's shape, declared rather than imported -------------------------------------- */

export interface VendorPoint {
  readonly time: number;
  readonly value: number | null;
}

export interface VendorResult {
  readonly plots?: Readonly<Record<string, readonly VendorPoint[]>>;
  readonly hlines?: readonly { readonly value?: number; readonly price?: number }[];
}

export interface VendorEntry {
  readonly id: string;
  readonly defaultInputs: Readonly<Record<string, StudyValue>>;
  readonly plotConfig?: readonly {
    readonly id: string;
    readonly display?: string;
    readonly lineWidth?: number;
  }[];
  readonly hlineConfig?: readonly { readonly price?: number }[];
  calculate(bars: readonly VendorBar[], inputs: Readonly<Record<string, StudyValue>>): VendorResult;
}

export interface IndicatorLibrary {
  readonly indicatorRegistry: readonly VendorEntry[];
}

export interface VendorBar {
  readonly time: number;
  readonly open: number;
  readonly high: number;
  readonly low: number;
  readonly close: number;
  readonly volume: number;
}

/* ---- bars in, points out -------------------------------------------------------------------- */

/**
 * ASCENDING BY TIME (ADAPT-05), because the library validates nothing about what it is given.
 *
 * A copy is sorted only on a descent, so the common path allocates nothing — and the SAME array is
 * what the points are then built on, or the index alignment the whole file rests on would be
 * against one order while the vendor computed against another.
 */
export function ascendingBars(bars: readonly Bar[]): readonly Bar[] {
  for (let index = 1; index < bars.length; index += 1) {
    if (bars[index].time < bars[index - 1].time) {
      return [...bars].sort((left, right) => left.time - right.time);
    }
  }
  return bars;
}

export const toVendorBars = (grid: readonly Bar[]): readonly VendorBar[] =>
  grid.map((bar) => ({
    time: bar.time as number,
    open: bar.open,
    high: bar.high,
    low: bar.low,
    close: bar.close,
    volume: bar.volume ?? 0,
  }));

/**
 * One point per BAR, timed by the bar and valued by the vendor.
 *
 * A vendor series shorter than the grid yields declared gaps for the rest; a value that is not a
 * finite number yields a point with no `value` at all.
 */
export function toPoints(
  grid: readonly Bar[],
  series: readonly VendorPoint[] | undefined,
): readonly Point[] {
  return grid.map((bar, index) => {
    const value = series === undefined ? undefined : series[index]?.value;
    return typeof value === 'number' && Number.isFinite(value)
      ? { time: utcSeconds(bar.time), value }
      : { time: utcSeconds(bar.time) };
  });
}

/* ---- the guide, recomputed from the LIVE result --------------------------------------------- */

const isNumber = (value: unknown): value is number => typeof value === 'number' && Number.isFinite(value);

/**
 * Levels come from three places, all measured on this vendor: `hlineConfig` (35 entries), the
 * result's own `hlines` (97), and HIDDEN CONSTANT PLOTS — the relative-strength family returns no
 * `hlines` at all and states its bands as `display:'none'` plots holding one value.
 */
function declaredLevels(entry: VendorEntry, result: VendorResult): readonly number[] {
  const levels = new Set<number>();
  for (const line of entry.hlineConfig ?? []) if (isNumber(line.price)) levels.add(line.price);
  for (const line of result.hlines ?? []) {
    const value = line.value ?? line.price;
    if (isNumber(value)) levels.add(value);
  }
  for (const config of entry.plotConfig ?? []) {
    if (config.display !== 'none' && config.lineWidth !== 0) continue;
    const values = (result.plots?.[config.id] ?? []).map((point) => point?.value).filter(isNumber);
    const first = values[0];
    if (values.length > 0 && values.every((v) => Math.abs(v - first) <= 1e-12 * Math.max(1, Math.abs(first)))) {
      levels.add(first);
    }
  }
  return [...levels];
}

/** "The declared level nearest the midpoint of the declared set." 30/50/70 -> 50; -100/0/100 -> 0. */
export function guideOf(levels: readonly number[]): number | undefined {
  if (levels.length === 0) return undefined;
  const mid = (Math.min(...levels) + Math.max(...levels)) / 2;
  return levels.reduce((best, level) => (Math.abs(level - mid) < Math.abs(best - mid) ? level : best));
}

/* ---- the values a chosen study computes with ------------------------------------------------ */

/** Every control that is not held keeps the vendor's own default — never a number written here. */
export function inputsFor(row: ManifestRow, entry: VendorEntry, values: StudyValues): Readonly<Record<string, StudyValue>> {
  const merged: Record<string, StudyValue> = { ...entry.defaultInputs };
  for (const control of row.inputs) {
    const held = values[control.id];
    if (held !== undefined) merged[control.id] = held;
  }
  return merged;
}

/* ---- one chosen study, as a drawable source ------------------------------------------------- */

/** Position-cycled, exactly as the lanes do it, so two plots of one study never share a hue. */
const PLOT_COLORS = ['#4c9aff', '#f5a623', '#c792ea', '#26c6da', '#66bb6a', '#ef5350'];

/**
 * ONE `calculate` PER PASS, and a throw is CACHED and rethrown.
 *
 * `resolveSources` asks each plot for its points separately, so a nine-plot study would otherwise
 * recompute nine times — and a study that throws would throw nine times before being reported once.
 * The pass is keyed on the bars ARRAY, which is the identity the workspace memoises on anyway.
 */
function passOf(entry: VendorEntry, inputs: Readonly<Record<string, StudyValue>>): (bars: readonly Bar[]) => {
  readonly grid: readonly Bar[];
  readonly result: VendorResult | null;
} {
  let lastBars: readonly Bar[] | null = null;
  let grid: readonly Bar[] = [];
  let result: VendorResult | null = null;
  let failure: Error | null = null;
  return (bars) => {
    if (bars !== lastBars) {
      lastBars = bars;
      grid = ascendingBars(bars);
      failure = null;
      result = null;
      try {
        result = entry.calculate(toVendorBars(grid), inputs);
      } catch (error) {
        failure = error instanceof Error ? error : new Error(String(error));
      }
    }
    // Rethrown, so the per-plot `try/catch` in `resolveSources` reports THIS study as unavailable
    // and leaves every other one drawn. The cache is what makes it one attempt instead of nine.
    if (failure !== null) throw failure;
    return { grid, result };
  };
}

/** A chosen study, with the values the tab is holding for it applied. */
export function studySourceFor(row: ManifestRow, entry: VendorEntry, values: StudyValues): PlottableSource {
  const pass = passOf(entry, inputsFor(row, entry, values));
  let last: VendorResult | null = null;
  return {
    id: row.id,
    label: row.fallbackLabel,
    placement: row.placement,
    /**
     * A GETTER, because a level can depend on a value the visitor edited, and `resolveSources`
     * reads it only after every plot has been computed — so the pass below is already warm. With
     * nothing computed yet the manifest's own default stands.
     */
    get guide(): number | undefined {
      return last === null ? row.guide : guideOf(declaredLevels(entry, last)) ?? row.guide;
    },
    series: (): readonly PlottedSeries[] =>
      row.plotIds.map((key, at) => ({
        spec: {
          id: seriesId(`${row.id}.${key}`),
          label: row.plotTitles[at] ?? key,
          shape: 'line' as const,
          color: PLOT_COLORS[at % PLOT_COLORS.length],
          lineWidth: 2 as const,
        },
        provider: {
          id: seriesId(`${row.id}.${key}`),
          compute: (bars: readonly Bar[]): readonly Point[] => {
            const { grid, result } = pass(bars);
            last = result;
            return toPoints(grid, result?.plots?.[key]);
          },
        },
      })),
  };
}

/** The study is chosen and the library is not here yet: keep the name, draw nothing, throw nothing. */
const pendingSourceFor = (row: ManifestRow): PlottableSource => ({
  id: row.id,
  label: row.fallbackLabel,
  placement: row.placement,
  series: () => [],
});

/* ---- what the demo mounts ------------------------------------------------------------------- */

/**
 * The names the menu lists BEFORE a byte of the library exists.
 *
 * `id` and `provider.id` carry the same string on purpose: the menu's DOM/test id is built from
 * `provider.id` while the pressed state and the persisted list key on `studyIdentity`. If those two
 * disagree nothing throws — the chip renders under one name and compares another, so the study
 * looks unselectable while the payload fills up correctly, which is the worst possible failure.
 */
export const catalogueEntries = (
  rows: readonly ManifestRow[] = MANIFEST_ROWS,
): readonly SeriesCatalogueEntry[] =>
  rows.map((row) => ({
    id: row.id,
    provider: { id: seriesId(row.id), compute: () => [] },
    label: row.fallbackLabel,
    category: row.category,
    hint:
      row.placement === 'over-price'
        ? 'Drawn on the price scale, because it is priced in the same unit.'
        : 'Drawn in a lane of its own, because it is not.',
  }));

/** One id, one answer — the shape the resolver takes, closed over the values the tab holds. */
export function sourceLookupFor(
  library: IndicatorLibrary | null,
  settings: Readonly<Record<string, StudySettings>> | undefined,
  rows: readonly ManifestRow[] = MANIFEST_ROWS,
): SourceLookup {
  const byId = new Map(rows.map((row) => [row.id, row] as const));
  const entries =
    library === null ? null : new Map(library.indicatorRegistry.map((entry) => [entry.id, entry] as const));
  return (id) => {
    const row = byId.get(id);
    if (row === undefined) return undefined;
    const entry = entries?.get(id);
    if (entry === undefined) return pendingSourceFor(row);
    return studySourceFor(row, entry, readStudyValues(settings?.[id], row));
  };
}

/**
 * KEEPS WHAT THIS BUILD STILL OFFERS, drops the rest — the injected migration point, and the only
 * place an id from a previous release can be translated.
 */
export const coerceIndicatorsFor =
  (rows: readonly ManifestRow[] = MANIFEST_ROWS) =>
  (raw: unknown, legacy: unknown): readonly string[] => {
    const offered = new Set(rows.map((row) => row.id));
    const source = Array.isArray(raw) ? raw : Array.isArray(legacy) ? legacy : [];
    const out: string[] = [];
    for (const held of source) {
      if (typeof held !== 'string' || !offered.has(held) || out.includes(held)) continue;
      out.push(held);
    }
    return out;
  };

/** The sibling: reading a parameter VALUE names the host's business, so the host reads it. */
export const coerceStudySettingsFor =
  (rows: readonly ManifestRow[] = MANIFEST_ROWS) =>
  (raw: unknown, indicators: readonly string[]): Readonly<Record<string, StudySettings>> => {
    const record = plainRecord(raw);
    if (record === null) return {};
    const byId = new Map(rows.map((row) => [row.id, row] as const));
    const wanted = new Set(indicators);
    const out: Record<string, StudySettings> = {};
    for (const id of Object.keys(record)) {
      const row = byId.get(id);
      if (row === undefined || !wanted.has(id)) continue;
      const values = readStudyValues(record[id], row);
      if (Object.keys(values).length > 0) out[id] = values;
    }
    return out;
  };

/* ---- loading, on demand --------------------------------------------------------------------- */

let pending: Promise<IndicatorLibrary> | null = null;
let library: IndicatorLibrary | null = null;

/**
 * THE ONLY RUNTIME MENTION OF THE LIBRARY, and it is behind the visitor's first study.
 *
 * Measured on this example: the dynamic import moves 1,096,779 B off the boot path — but only while
 * the bundler splits. `scripts/boot-chunk.mjs` is the ceiling that says so out loud.
 *
 * A DROPPED NETWORK IS NOT A PERMANENT VERDICT: the promise is forgotten on failure so the next
 * pick tries again, and until then the workspace mounts and draws with an empty catalogue.
 */
export function loadIndicatorLibrary(): Promise<IndicatorLibrary> {
  pending ??= import('lightweight-charts-indicators').then(
    (module) => {
      library = module as unknown as IndicatorLibrary;
      return library;
    },
    (error: unknown) => {
      pending = null;
      throw error;
    },
  );
  return pending;
}

/** `null` until the chunk has arrived. Read by the composition, never awaited by it. */
export const loadedIndicatorLibrary = (): IndicatorLibrary | null => library;
